### ISSUE TITLE
beam scales are incorrect

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/eidos#14]
@kmbasad As discussed this is a bug that may be contributing to @IanHeywood's flux scale headaches. -d stretches the beam instead of resampling it. Not sure which value of -d is accurate now - may explain why the beam never improved leakage into Stokes V for me:
![image](https://user-images.githubusercontent.com/7934586/52204196-2ac32a80-287c-11e9-897b-2bc01e2d40e9.png)
![image](https://user-images.githubusercontent.com/7934586/52204221-3e6e9100-287c-11e9-992c-b82adbfa5988.png)

**Comment by kmbasad** [comment]
This has been fixed in the new version: 1.0.
