### ISSUE TITLE
Error if Stokes I is defined

### ISSUE THREAD

**Issue by hrkloeck** [ratt-ru/eidos#17]
eidos -p 256 -d 10 -f 1070
Saved Real part as primary_beam_mh_1070MHz_10deg_re.fits
Saved Imaginary part as primary_beam_mh_1070MHz_10deg_im.fits

eidos -p 256 -d 10 -f 1070 -S I
Traceback (most recent call last):
  File "/anaconda2/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/anaconda2/lib/python2.7/site-packages/eidos/create_beam.py", line 100, in main
    data_M = jones_to_mueller_all(data)
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by kmbasad** [comment]
Really sorry. That was a silly mistake. Should be fixed now.

**Comment by hrkloeck** [comment]
Hi Khan,

	thank you very much for your reply. Actually it was also complaining that it could not find the
meerkat_beam_coeffs_ah_zp_dct.npy  meerkat_beam_coeffs_em_zp_dct.npy files and I copied the
entire /data directory into the site-packages/eidos

One maybe silly question, I guess your tool is also used to generate the PB for stimela environment and as input for the direction depended calibration
in MeerKATHI pipeline, or ? If so, would be interesting to feed in the PB parameter for the SKA - Prototyp dish in the future, or?

Cheers, Hans

--------------------------------------------------------
Hans-Rainer Klöckner
--------------------------------------------------------
Max-Planck-Institut für Radioastronomie
Auf dem Hügel 69
53121 Bonn
Germany
+49 (0)228 525-314
hrk@mpifr-bonn.mpg.de
--------------------------------------------------------
